import utils as util
import sys
response = {
    "error": "",
    "message": "",
    "request_id": "ac704e0020c91f99d076dfb17dd31200",
    "response": [
        {
            "escrow_detail": {
                "buyer_payment_info": {
                    "buyer_payment_method": "ShopeePay Linked Bank Account",
                    "buyer_service_fee": 0,
                    "buyer_tax_amount": 0,
                    "buyer_total_amount": 48440,
                    "credit_card_promotion": 0,
                    "icms_tax_amount": 0,
                    "import_tax_amount": 0,
                    "initial_buyer_txn_fee": 0,
                    "insurance_premium": 0,
                    "iof_tax_amount": 0,
                    "is_paid_by_credit_card": False,
                    "merchant_subtotal": 52600,
                    "seller_voucher": 0,
                    "shipping_fee": 2000,
                    "shipping_fee_sst_amount": 0,
                    "shopee_coins_redeemed": -900,
                    "shopee_voucher": -5260
                },
                "buyer_user_name": "ng_phuong48",
                "order_income": {
                    "actual_shipping_fee": 0,
                    "buyer_paid_shipping_fee": 2000,
                    "buyer_payment_method": "ShopeePay Linked Bank Account",
                    "buyer_total_amount": 48440,
                    "buyer_transaction_fee": 0,
                    "campaign_fee": 0,
                    "coins": 400,
                    "commission_fee": 0,
                    "cost_of_goods_sold": 23700,
                    "credit_card_promotion": 0,
                    "credit_card_transaction_fee": 848,
                    "cross_border_tax": 0,
                    "delivery_seller_protection_fee_premium_amount": 0,
                    "drc_adjustable_refund": 25510,
                    "escrow_amount": 100,
                    "escrow_tax": 0,
                    "estimated_shipping_fee": 17000,
                    "final_escrow_product_gst": 0,
                    "final_escrow_shipping_gst": 0,
                    "final_product_protection": 0,
                    "final_product_vat_tax": 0,
                    "final_return_to_seller_shipping_fee": 0,
                    "final_shipping_fee": 15000,
                    "final_shipping_vat_tax": 0,
                    "fsf_seller_protection_fee_claim_amount": 0,
                    "instalment_plan": "N/A",
                    "items": [
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 300,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 1470,
                            "discounted_price": 14700,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 24173211461,
                            "item_name": "HANBOLI Dụng cụ uốn mi mini cầm tay bằng thép không gỉ",
                            "item_sku": "SXY472-08",
                            "model_id": 99542389678,
                            "model_name": "Đen",
                            "model_sku": "SXY472001",
                            "original_price": 21000,
                            "quantity_purchased": 1,
                            "seller_discount": 6300,
                            "selling_price": 14700,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 0,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 300,
                            "discounted_price": 3000,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 24822331570,
                            "item_name": "HANBOLI Phim hoạt hình tình yêu lược nhỏ",
                            "item_sku": "HZMBB0198-08",
                            "model_id": 245581210110,
                            "model_name": "Hồng",
                            "model_sku": "HZMBB0198001",
                            "original_price": 4000,
                            "quantity_purchased": 1,
                            "seller_discount": 1000,
                            "selling_price": 3000,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 500,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 2890,
                            "discounted_price": 28900,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 25819910186,
                            "item_name": "HANBOLI bộ cọ trang điểm 13 cây",
                            "item_sku": "SXY482-08",
                            "model_id": 232615005081,
                            "model_name": "Hồng",
                            "model_sku": "SXY482006",
                            "original_price": 41000,
                            "quantity_purchased": 1,
                            "seller_discount": 12100,
                            "selling_price": 28900,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 100,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 600,
                            "discounted_price": 6000,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 25823200241,
                            "item_name": "HANBOLI Đơn đa chức năng cọ môi tròn",
                            "item_sku": "SXY481-08",
                            "model_id": 147257500156,
                            "model_name": "Cọ môi",
                            "model_sku": "SXY481001",
                            "original_price": 8000,
                            "quantity_purchased": 1,
                            "seller_discount": 2000,
                            "selling_price": 6000,
                            "shopee_discount": 0
                        }
                    ],
                },
                "order_sn": "2405017HD347PQ",
                "return_order_sn_list": [
                    "2405060KVC6EQB3"
                ]
            }
        },
        {
            "escrow_detail": {
                "buyer_payment_info": {
                    "buyer_payment_method": "ShopeePay Linked Bank Account",
                    "buyer_service_fee": 0,
                    "buyer_tax_amount": 0,
                    "buyer_total_amount": 48440,
                    "credit_card_promotion": 0,
                    "icms_tax_amount": 0,
                    "import_tax_amount": 0,
                    "initial_buyer_txn_fee": 0,
                    "insurance_premium": 0,
                    "iof_tax_amount": 0,
                    "is_paid_by_credit_card": False,
                    "merchant_subtotal": 52600,
                    "seller_voucher": 0,
                    "shipping_fee": 2000,
                    "shipping_fee_sst_amount": 0,
                    "shopee_coins_redeemed": -900,
                    "shopee_voucher": -5260
                },
                "buyer_user_name": "ng_phuong48",
                "order_income": {
                    "actual_shipping_fee": 0,
                    "buyer_paid_shipping_fee": 2000,
                    "buyer_payment_method": "ShopeePay Linked Bank Account",
                    "buyer_total_amount": 48440,
                    "buyer_transaction_fee": 0,
                    "campaign_fee": 0,
                    "coins": 400,
                    "commission_fee": 0,
                    "cost_of_goods_sold": 23700,
                    "credit_card_promotion": 0,
                    "credit_card_transaction_fee": 848,
                    "cross_border_tax": 0,
                    "delivery_seller_protection_fee_premium_amount": 0,
                    "drc_adjustable_refund": 25510,
                    "escrow_amount": 10,
                    "escrow_tax": 0,
                    "estimated_shipping_fee": 17000,
                    "final_escrow_product_gst": 0,
                    "final_escrow_shipping_gst": 0,
                    "final_product_protection": 0,
                    "final_product_vat_tax": 0,
                    "final_return_to_seller_shipping_fee": 0,
                    "final_shipping_fee": 15000,
                    "final_shipping_vat_tax": 0,
                    "fsf_seller_protection_fee_claim_amount": 0,
                    "instalment_plan": "N/A",
                    "items": [
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 300,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 1470,
                            "discounted_price": 14700,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 24173211461,
                            "item_name": "HANBOLI Dụng cụ uốn mi mini cầm tay bằng thép không gỉ",
                            "item_sku": "SXY472-08",
                            "model_id": 99542389678,
                            "model_name": "Đen",
                            "model_sku": "SXY472001",
                            "original_price": 21000,
                            "quantity_purchased": 1,
                            "seller_discount": 6300,
                            "selling_price": 14700,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 0,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 300,
                            "discounted_price": 3000,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 24822331570,
                            "item_name": "HANBOLI Phim hoạt hình tình yêu lược nhỏ",
                            "item_sku": "HZMBB0198-08",
                            "model_id": 245581210110,
                            "model_name": "Hồng",
                            "model_sku": "HZMBB0198001",
                            "original_price": 4000,
                            "quantity_purchased": 1,
                            "seller_discount": 1000,
                            "selling_price": 3000,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 500,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 2890,
                            "discounted_price": 28900,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 25819910186,
                            "item_name": "HANBOLI bộ cọ trang điểm 13 cây",
                            "item_sku": "SXY482-08",
                            "model_id": 232615005081,
                            "model_name": "Hồng",
                            "model_sku": "SXY482006",
                            "original_price": 41000,
                            "quantity_purchased": 1,
                            "seller_discount": 12100,
                            "selling_price": 28900,
                            "shopee_discount": 0
                        },
                        {
                            "activity_id": 0,
                            "activity_type": "",
                            "ams_commission_fee": 0,
                            "discount_from_coin": 100,
                            "discount_from_voucher_seller": 0,
                            "discount_from_voucher_shopee": 600,
                            "discounted_price": 6000,
                            "is_b2c_shop_item": False,
                            "is_main_item": False,
                            "item_id": 25823200241,
                            "item_name": "HANBOLI Đơn đa chức năng cọ môi tròn",
                            "item_sku": "SXY481-08",
                            "model_id": 147257500156,
                            "model_name": "Cọ môi",
                            "model_sku": "SXY481001",
                            "original_price": 8000,
                            "quantity_purchased": 1,
                            "seller_discount": 2000,
                            "selling_price": 6000,
                            "shopee_discount": 0
                        }
                    ],
                },
                "order_sn": "2405017HD347RR",
                "return_order_sn_list": [
                    "2405017HD347PQ"
                ]
            }
        }
    ]
}

escrow_details = [escrow['escrow_detail'] for escrow in response['response']]
order_sn = "2405017HD347RR"
#print(escrow_details)
escrow_sns = [escrow['order_sn'] for escrow in escrow_details]
order_sn = "2405017HD347PQ"
print(escrow_sns)
escrow_index = escrow_sns.index(order_sn)

escrow = escrow_details[escrow_index]

order_escrow = escrow['order_income']['escrow_amount']
print(order_escrow)

for item in escrow['order_income']['items']:
    print(item['item_id'])
